### ISSUE TITLE
My. net6 program uses the Tesseract library, which works fine under Windows, but fails under Linux

### ISSUE THREAD

**Issue by xuxuanqi** [DanBloomberg/leptonica#705]
My. net6 program uses the Tesseract library, which works fine under Windows, but fails under Linux.

Error reporting:
    System.DllNotFoundException: Failed to find library "libleptonica-1.82.0.so" for platform x64.
   at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformName)
   at InteropRuntimeImplementer.LeptonicaApiSignaturesInstance.LeptonicaApiSignaturesImplementation..ctor(LibraryLoader loader)

**Comment by xuxuanqi** [comment]
I want to know how to solve this problem
